### ISSUE TITLE
[Possible Improvement]: Instant Finish

### ISSUE THREAD

**Issue by xesdoog** [YimMenu-Lua/PayphoneHits#1]
Hello Arthur,

I messed around with payphone hits before by setting script locals but I've never managed to set the bonus and also my method was weird, most of the time it only finished the hit one time then it failed every next hit.

A few minutes ago I used your release to request a payphone hit but realized that there's no instant finish so I used your option to complete the assassination bonus then used my old method to instantly finish the hit. It worked every time **BUT** after 3 hits in a row it started spamming my log with this error `[17:28:34.8399921][WARN/shop_controller.hpp:24] Received transaction rate limit` 
This is probably because I disabled the cooldown? I don't know. The console kept printing that error for over 10 minutes so I panicked and left the session 😅

I called this to instantly finish the hit:

```lua
    if ImGui.Button("Instant Finish Payphone Hit") then
      script.run_in_fiber(function()
        if SCRIPT.GET_NUMBER_OF_THREADS_RUNNING_THE_SCRIPT_WITH_THIS_HASH(joaat("fm_content_payphone_hit")) > 0 then
          if NETWORK.NETWORK_IS_HOST_OF_THIS_SCRIPT() then
            locals.set_int("fm_content_payphone_hit", 5675 + 683, 3)
          end
        end
      end)
    end
```

I forgot how I even came up with that 3 in the `set_int` call but I found Local_5675.f_683 in func_8 in `fm_content_payphone_hit.c`

**Comment by ShinyWasabi** [comment]
What you do in your example is basically setting the end reason of the mission. Every `fm_mission_*` script has this logic. I even use it in my Random Events script to kill an event. 3 means that the mission is completed and the script can be gracefully terminated.
I'm not on my PC, so I can't give it a try. If it's working, tell me and I'll add it or you can make a PR.

Also, I like the way you check the script host. This is required as `Local_5675` is a host broadcast data variable, meaning only the host can modify it. I should add this check for Assassination Bonus as well.
BTW, using `NETWORK_IS_HOST_OF_THIS_SCRIPT` will fail because `run_in_fiber` executes your code inside the `main_persistent` script. So you should either use `NETWORK_GET_HOST_OF_SCRIPT` or `execute_as_script` with `fm_content_payphone_hit`.

> It worked every time BUT after 3 hits in a row it started spamming my log with this error.

That's probably because you triggered too many transactions in a short period of time. You shouldn't worry.

**Comment by xesdoog** [comment]
Thanks a lot! You've taught me many things since I've started writing Lua code for YimMenu and I appreciate you for that.

I didn't want to open a PR because I wasn't sure if what I did was safe but it does indeed work though me being reckless and impatient, I disabled the cooldown and finished 2 or 3 hits in a row without even moving away from the payphone.
